### ISSUE TITLE
Angular 7 service支援？

### ISSUE THREAD

**Issue by axacheng** [TapPay/tappay-nodejs#1]
請問我該怎麼使用 angular 7 framework 做 TPDirect.card.setup 與後續的TPDirect.card.getPrime 呼叫呢？我看到 tappay-nodejs 裡面有 TapPayServices.d.ts 定義檔案，但確定怎麼整合到 angular 裡面，請問有範例程式嗎？ 

感謝

**Comment by Yu-Jack** [comment]
@axacheng 你好

TapPay 主要有分兩段
一段是 Get Prime (設置頁面讓使用者填信用卡）
一段是 Pay by Prime (Get Prime 之後會取得的東西，並由你的後端伺服器往 TapPay 伺服器送請求)
我們 TapPayService.d.ts 定義檔案裡面是管控 Pay by Prime 後面那段的程式
跟前端 TPDirect.card.setup & TPDirect.card.getPrime 是沒有任何關係的
那目前前端 SDK 的 Get Prime 也尚未有定義檔，所以這個部分很抱歉可能無法符合你的預期需求 😢 

謝謝！

**Comment by axacheng** [comment]
太感謝您了Jack. 看了你們的文件我覺得你們的架構蠻漂亮的彈性與延伸性很強。但，目前看來只能參考你們寫的 vanilla javascript 範例這方式了。

其實我昨天也有成功在angular 7 project 裡面的 index.html 測試了getPrime ，也成功拿到了Prime token和成功做了幾個 DirectPay transactions 的測試，但LinePay因為3D問題所以失敗...

想再請問一下，前端SDK日後做Typescript 的定義檔案這部分會在你們的開發 roadmap裡面嗎？
如果有的話，我想說等你們好我在整合進angular service 裡面。

或者是，我們自己在切出一層架構(可能很笨) ，架構邏輯如下，請您幫我review是否可行？

步驟1.) 用nodejs express 架一個輕量的web server, 裡面的 index.html就直接改寫tappay-web-example 裡面的index.html
步驟2.) 在同一個nodejs express 裡面直接呼叫 TapPay = require('tappay-nodejs') 去做後端的Pay By Prime.
步驟3.) 在我們angular 7 webapp 裡面的結帳頁面放一個 <a href=$link> 

步驟4.) 消費者的瀏覽器直接點那個 $link, 連到上面步驟1提到的 nodejs express web server index.html去讓消費者填好卡號，然後form onsubmit 後直接把 form input欄位裡面的值送去 TPDirect vanilla Javascript SDK去取得 Prime

步驟5.) 上述步驟拿到 Prime token後，再把這Prime token 丟到步驟2 nodejs express 另外的一個route 把Prime token擷取出來，丟到nodejs 的 Pay By Prime workflow 去做最後的銀行授權部分。 


不知道這架構是否可行？或是您有更聰明的方式呢？


感謝

**Comment by Yu-Jack** [comment]
@axacheng 您好
您的這個架構是可以的
我們有些客戶也是有在 app 上面使用 web view 去進行付款
得到結果之後再跳回去 APP

但您要注意的是，連線過去的網站記得要是 https
這也是為了你的 web view 的安全，切務必記得這件事 😄

**Comment by axacheng** [comment]
太棒了！感謝您 🙏
